### ISSUE TITLE
Error (Bad): Object reference not set to an instance of an object (NullReferenceException)

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/binding-tools-for-swift#148]
Test case: [AEXML.zip](https://github.com/xamarin/maccore/files/1904092/AEXML.zip)

To repro: unzip & `make all TOOL_LIB=/path/to/swift-o-matic`

Full log: https://gist.github.com/rolfbjarne/b10344d78499d00cd8ba5a0c22a802f1

Source: https://github.com/tadija/AEXML

**Comment by stephen-hawley** [comment]
Fixed in pr [380](https://github.com/xamarin/binding-tools-for-swift/pull/380)
