### ISSUE TITLE
Error (Bad): Specified argument was out of the range of valid values. Parameter name: depth (ArgumentOutOfRangeException)

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/binding-tools-for-swift#149]
Test case: [Dollar.zip](https://github.com/xamarin/maccore/files/1903833/Dollar.zip)

Repro: unzip & `make all TOOL_LIB=/path/to/swift-o-matic`

Result: https://gist.github.com/rolfbjarne/ca4673ab7b8698abe91aefcad856b76c

Source: https://github.com/ankurp/Dollar

**Comment by stephen-hawley** [comment]
Fixed in PR [381](https://github.com/xamarin/binding-tools-for-swift/pull/381)
