### ISSUE TITLE
Error while making swiftglue

### ISSUE THREAD

**Issue by roubachof** [xamarin/binding-tools-for-swift#185]
So I became way to excited and started messing around with my VM to install all prerequisites.
Now all is ok except for the Xamarin.iOS version. 12.0.0.15 is requested but I have 13.8 installed.
Issue is, 12.0.0.15 is incompatible with Catalina.
So I ignored this specific dependency with export IGNORE_XI.

But now I have those errors while making swiftglue:

```
bindingmetadata.iphone.swift:15:8: error: no such module 'BackgroundTasks'
import BackgroundTasks
       ^
bindingmetadata.iphone.swift:15:8: error: no such module 'BackgroundTasks'
import BackgroundTasks
       ^
make[1]: *** [bin/Release/iphone/i386/XamGlue] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [bin/Debug/iphone/x86_64/XamGlue] Error 1
bindingmetadata.iphone.swift:15:8: error: no such module 'BackgroundTasks'
import BackgroundTasks
       ^
bindingmetadata.iphone.swift:15:8: error: no such module 'BackgroundTasks'
import BackgroundTasks
       ^
make[1]: *** [bin/Debug/iphone/arm64/XamGlue] Error 1
make[1]: *** [bin/Debug/iphone/armv7/XamGlue] Error 1
bindingmetadata.macos.swift:9:8: error: no such module 'AuthenticationServices'
import AuthenticationServices
       ^
bindingmetadata.iphone.swift:15:8: error: no such module 'BackgroundTasks'
import BackgroundTasks
       ^
make[1]: *** [bin/Release/mac/x86_64/XamGlue] Error 1
make[1]: *** [bin/Debug/iphone/i386/XamGlue] Error 1
bindingmetadata.macos.swift:9:8: error: no such module 'AuthenticationServices'
import AuthenticationServices
       ^
bindingmetadata.iphone.swift:15:8: error: no such module 'BackgroundTasks'
import BackgroundTasks
       ^
make[1]: *** [bin/Debug/mac/x86_64/XamGlue] Error 1
make[1]: *** [bin/Debug/iphone/armv7s/XamGlue] Error 1
make: *** [all] Error 2
```

Does it have something to do with the Xamarin.iOS version used?

**Comment by rolfbjarne** [comment]
> Does it have something to do with the Xamarin.iOS version used?

Yes, these errors are because you're not using the right Xamarin.iOS version.

Did you actually try installing Xamarin.iOS 12.0.0.15 to see if it works or not? It's not 100% usable on Catalina, but the parts that the Binding Tools for Swift need might work fine.

**Comment by roubachof** [comment]
As I said, you can’t install Xamarin.iOS 12.0.0.15 on Catalina.
So I guess another strong prerequisite is Mojave.
