### ISSUE TITLE
binding tools not working on macOS 10.14.6

### ISSUE THREAD

**Issue by aimore** [xamarin/binding-tools-for-swift#215]
`192-168-1-42:Downloads aimoresc$ cd binding-tools-for-swift
192-168-1-42:binding-tools-for-swift aimoresc$ make
fatal: not a git repository (or any of the parent directories): .git
/bin/sh: ((: > 999 : syntax error: operand expected (error token is "> 999 ")
Checking system...
    Found macOS 10.14.6 (at least 10.14.3 is required)
    You must install Xcode (10.2.1) in /Applications/Xcode_10.2.1.app. You can download Xcode 10.2.1 here: https://developer.apple.com/downloads/index.action?name=Xcode
    Could not find XcodeSystemResources.pkg (which contains CoreSimulator.framework) in /Applications/Xcode_10.2.1.app/Contents/Developer (/Applications/Xcode_10.2.1.app/Contents/Resources/Packages/XcodeSystemResources.pkg doesn't exist).
    Found Mono 6.4.0.208 (at least 6.4.0.0 and not more than 6.4.0.999 is required)
    Your Xamarin.iOS version is too new, max version is 12.0.0.15, found 13.6.0.12.
    You can execute ./jenkins/system-dependencies.sh --provision-xi to automatically install Xamarin.iOS.
    You may also edit Make.config and change MAX_XI_VERSION to your actual version to continue the
    build (unless you're on a release branch). Once the build completes successfully, please
    commit the new MAX_XI_VERSION value.
    Alternatively you can export IGNORE_XI=1 to skip this check.
    You must install Xamarin.Mac 5.0.0.0, no version of Xamarin.Mac was detected.
System check failed
make: *** [check-system] Error 1`

**Comment by stephen-hawley** [comment]
Hi @aimore - thanks for you report.
In this case, this is not an OS related issue.
In order to build BTfS you need to install:
- Xcode 10.2.1 which you can get [here](https://developer.apple.com/downloads/index.action?name=Xcode)
- Xamarin.iOS 12.0.0.15 (or you can change MAX_XI_VERSION in Make.config)
- Xamarin.Mac 5.0.0

**Comment by chamons** [comment]
Those appear to be results of you attempting to build the binding tools for swift? 

If you want to work on this project I would suggest reading the [quickstart](https://github.com/xamarin/binding-tools-for-swift/blob/master/QUICKSTART.md)

and posting any questions on 

https://gitter.im/xamarin/xamarin-macios

Issues aren't the best way to contact the team on problems building.

**Comment by aimore** [comment]
Hi @stephen-hawley,
I have changed  already the make.config file, installed the older version of Xcode and changed the path.
Here you can find the edited Make.config file
https://gist.github.com/aimore/96fa5555d24aa0f9e287fc3268751589

@chamons  I did read the quick start and still does not help or solve the issue I am facing
Not only once but many times about the progress on the Xamarin official Swift support, the reply only came after I post this issue.
The General [Roadmap #165](https://github.com/xamarin/binding-tools-for-swift/issues/165) posted here as an issue lacks clarity and direction where it's going.

**Comment by chamons** [comment]
Issues aren't the best way of asking questions of this type. I'm sorry we didn't respond to you on gitter.

Right now, the major item listed on the [roadmap](https://github.com/xamarin/binding-tools-for-swift/issues/165) being worked on is" Support for Protocols with Associated Types".

The tool currently requires knowledge of command line tools to run. One of the times on the roadmap - "Project and MSBuild support to make it easier to use" should improve this, but until then you'll need to get your hands dirty.
