### ISSUE TITLE
cannot downgrade to xamarin.iOS 12.0.0.15

### ISSUE THREAD

**Issue by mauro3005** [xamarin/binding-tools-for-swift#471]
Pending issue

### Steps to Reproduce
1. download zip file of binding-tools-for-swift-swift-5.0-last-stable
2. update make.config as follows to set XCODE_VERSION=10.2 and Root for xcode (Also tried initially with xcode 12.0.1 and had same result.
# The Xcode we need.
# Use the path as used in the Azure Pipelines vm images.
XCODE_VERSION=10.2
XCODE_URL=http://xamarin-storage/bot-provisioning/xcodes/Xcode_10.2.1.xip
XCODE_DEVELOPER_ROOT=/Users/dtx0djq/Downloads/Xcode.app/Contents/Developer

3. cd into root folder of project binding-tools-for-swift-swift-5.0-last-stable
4. type "make" and the result is below with log output
WKSP000B4400:binding-tools-for-swift-swift-5.0-last-stable dtx0djq$ make
fatal: not a git repository (or any of the parent directories): .git
/bin/sh: ((: > 999 : syntax error: operand expected (error token is "> 999 ")
Checking system...
    Found macOS 10.15.7 (at least 10.14.3 is required)
        Deleted Xcode cache file: /var/folders/jr/5qwlqyy17b12_fzw_1r40ywc70pzkf/T/com.apple.dt.Xcode.InstallCheckCache_MobileDevice_19H2_10E125 (this is normal)
        Deleted Xcode cache file: /var/folders/jr/5qwlqyy17b12_fzw_1r40ywc70pzkf/T/com.apple.dt.Xcode.InstallCheckCache_com.apple.pkg.MobileDeviceDevelopment_19H2_10E125 (this is normal)
        Deleted Xcode cache file: /var/folders/jr/5qwlqyy17b12_fzw_1r40ywc70pzkf/T/com.apple.dt.Xcode.InstallCheckCache_CoreSim_19H2_10E125 (this is normal)
    Found Xcode 10.2 in /Users/dtx0djq/Downloads/Xcode.app
    You should have exactly CoreSimulator.framework version 587.35 (found 732.17). Execute './jenkins/system-dependencies.sh --provision-xcode' to install the expected version.
    Ignoring the Mono dependency because the IGNORE_MONO variable is set.
    Ignoring the Xamarin.iOS dependency because the IGNORE_XI variable is set.
    Ignoring the Xamarin.Mac dependency because the IGNORE_XM variable is set.
    Found CMake 3.18.3 (at least 3.15.5 is required)
System check succeeded
Building Binding Tools For Swift 0.2.0.
./jenkins/build-swift.sh
✅ No need to build swift, we're already using a packaged version
./jenkins/build.sh
++ dirname ./jenkins/build.sh
+ cd ./jenkins/..
++ pwd
+ WORKSPACE=/Users/dtx0djq/Downloads/binding-tools-for-swift-swift-5.0-last-stable
+ nuget restore tom-swifty.sln
MSBuild auto-detection: using msbuild version '15.0' from '/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/15.0/bin'.
All packages listed in packages.config are already installed.
+ cd /Users/dtx0djq/Downloads/binding-tools-for-swift-swift-5.0-last-stable/plist-swifty
+ msbuild
Microsoft (R) Build Engine version 16.6.0 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 10/14/2020 8:38:27 PM.
Project "/Users/dtx0djq/Downloads/binding-tools-for-swift-swift-5.0-last-stable/plist-swifty/plist-swifty.csproj" on node 1 (default targets).
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
CoreCompile:
Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
_CopyFilesMarkedCopyLocal:
  Touching "/Users/dtx0djq/Downloads/binding-tools-for-swift-swift-5.0-last-stable/plist-swifty/obj/x86/Debug/plist-swifty.csproj.CopyComplete".
CopyFilesToOutputDirectory:
  plist-swifty -> /Users/dtx0djq/Downloads/binding-tools-for-swift-swift-5.0-last-stable/plist-swifty/bin/Debug/plist-swifty.exe
Done Building Project "/Users/dtx0djq/Downloads/binding-tools-for-swift-swift-5.0-last-stable/plist-swifty/plist-swifty.csproj" (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.65
+ cd /Users/dtx0djq/Downloads/binding-tools-for-swift-swift-5.0-last-stable/type-o-matic
+ msbuild
Microsoft (R) Build Engine version 16.6.0 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 10/14/2020 8:38:28 PM.
Project "/Users/dtx0djq/Downloads/binding-tools-for-swift-swift-5.0-last-stable/type-o-matic/type-o-matic.csproj" on node 1 (default targets).
Project "/Users/dtx0djq/Downloads/binding-tools-for-swift-swift-5.0-last-stable/type-o-matic/type-o-matic.csproj" (1) is building "/Users/dtx0djq/Downloads/binding-tools-for-swift-swift-5.0-last-stable/Dynamo/Dynamo.csproj" (2:2) on node 1 (default targets).
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
CoreCompile:
Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
CopyFilesToOutputDirectory:
  Dynamo -> /Users/dtx0djq/Downloads/binding-tools-for-swift-swift-5.0-last-stable/Dynamo/bin/Debug/Dynamo.dll
Done Building Project "/Users/dtx0djq/Downloads/binding-tools-for-swift-swift-5.0-last-stable/Dynamo/Dynamo.csproj" (default targets).
Project "/Users/dtx0djq/Downloads/binding-tools-for-swift-swift-5.0-last-stable/type-o-matic/type-o-matic.csproj" (1) is building "/Users/dtx0djq/Downloads/binding-tools-for-swift-swift-5.0-last-stable/SwiftRuntimeLibrary/SwiftRuntimeLibrary.csproj" (3:2) on node 1 (default targets).
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
CoreCompile:
Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
CopyFilesToOutputDirectory:
  SwiftRuntimeLibrary -> /Users/dtx0djq/Downloads/binding-tools-for-swift-swift-5.0-last-stable/SwiftRuntimeLibrary/bin/Debug/SwiftRuntimeLibrary.dll
Done Building Project "/Users/dtx0djq/Downloads/binding-tools-for-swift-swift-5.0-last-stable/SwiftRuntimeLibrary/SwiftRuntimeLibrary.csproj" (default targets).
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
CoreCompile:
Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
_CopyFilesMarkedCopyLocal:
  Touching "/Users/dtx0djq/Downloads/binding-tools-for-swift-swift-5.0-last-stable/type-o-matic/obj/x86/Debug/type-o-matic.csproj.CopyComplete".
CopyFilesToOutputDirectory:
  type-o-matic -> /Users/dtx0djq/Downloads/binding-tools-for-swift-swift-5.0-last-stable/type-o-matic/bin/Debug/type-o-matic.exe
Done Building Project "/Users/dtx0djq/Downloads/binding-tools-for-swift-swift-5.0-last-stable/type-o-matic/type-o-matic.csproj" (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.90
+ cd /Users/dtx0djq/Downloads/binding-tools-for-swift-swift-5.0-last-stable/swiftglue
+ make generate-swift-bindings
make[1]: Nothing to be done for `generate-swift-bindings'.
+ make all -j8
SWIFTC [mac/x86_64/Debug]  XamGlue
SWIFTC [mac/x86_64/Release]  XamGlue
SWIFTC [iphone/i386/Debug]  XamGlue
SWIFTC [iphone/x86_64/Debug]  XamGlue
SWIFTC [iphone/arm64/Debug]  XamGlue
SWIFTC [iphone/armv7/Debug]  XamGlue
SWIFTC [iphone/armv7s/Debug]  XamGlue
SWIFTC [iphone/i386/Release]  XamGlue
bindingmetadata.iphone.swift:5:8: error: no such module 'Accessibility'
import Accessibility
       ^
bindingmetadata.iphone.swift:5:8: error: no such module 'Accessibility'
import Accessibility
       ^
bindingmetadata.iphone.swift:5:8: error: no such module 'Accessibility'
import Accessibility
       ^
make[1]: *** [bin/Debug/iphone/armv7s/XamGlue] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [bin/Debug/iphone/armv7/XamGlue] Error 1
make[1]: *** [bin/Debug/iphone/arm64/XamGlue] Error 1
bindingmetadata.iphone.swift:5:8: error: no such module 'Accessibility'
import Accessibility
       ^
bindingmetadata.iphone.swift:5:8: error: no such module 'Accessibility'
import Accessibility
       ^
make[1]: *** [bin/Debug/iphone/i386/XamGlue] Error 1
bindingmetadata.iphone.swift:5:8: error: no such module 'Accessibility'
import Accessibility
       ^
make[1]: *** [bin/Release/iphone/i386/XamGlue] Error 1
make[1]: *** [bin/Debug/iphone/x86_64/XamGlue] Error 1
bindingmetadata.macos.swift:9:8: error: no such module 'AuthenticationServices'
import AuthenticationServices
       ^
bindingmetadata.macos.swift:9:8: error: no such module 'AuthenticationServices'
import AuthenticationServices
       ^
make[1]: *** [bin/Debug/mac/x86_64/XamGlue] Error 1
make[1]: *** [bin/Release/mac/x86_64/XamGlue] Error 1
make: *** [all] Error 2

### Expected Behavior
expected make to build source code and me be able to use tom-swifty per instruction on swift framework
### Actual Behavior
was not able to compile source code
### Environment
MacOS: 10.15.7 (19H2)

I'm not sure if the issue is with my Xamarin.iOS being 14.0.0.0 because i have used every other make parameter except this one that is not compatible with MacOS 10.15.7 I found this out by manually downloading the Xamarin.iOS pkg and getting the message that it's not compatible with my MacOS version

        Downloading Xamarin.iOS 12.0.0.15 from https://download.visualstudio.microsoft.com/download/pr/28396824-ecde-429e-9693-0da9382e1474/debd3c099bf5a516b964675c2628e601/xamarin.ios-12.0.0.15.pkg to /tmp/x-provisioning...
        Found xamarin.ios-12.0.0.15.pkg (12.0.0.15) in your ~/Downloads folder, copying that version to /tmp/x-provisioning/xamarin.ios-12.0.0.15.pkg instead of re-downloading it.
        Installing Xamarin.iOS 12.0.0.15 from /Users/dtx0djq/Downloads/xamarin.ios-12.0.0.15.pkg...
Password:
installer: Package name is Xamarin.iOS
installer: Upgrading at base path /
installer: The upgrade failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. The package is attempting to install content to the system volume.)

Is anyone with Mac OS Catalina able to get binding-tools-for-swift-swift running yet?

**Comment by chamons** [comment]
Thanks for your interest in Binding Tools for Swift. 

It is a known issues that one can not build on Catalina against Xcode 10.2.

We are actively working on moving to build against Xcode 12.0.

If you have questions on how to build and contribute to this project, feel free to drop by [our discord](https://aka.ms/dotnet-discord). That is a better place to get help building the project.
