### ISSUE TITLE
SwiftInterfaceParser should use more string constants

### ISSUE THREAD

**Issue by stephen-hawley** [xamarin/binding-tools-for-swift#525]
make constants for strings used in attributes and element names, especially the `"IGNORE"` string which is partially done.

**Comment by ShrillShrestha** [comment]
Hi. I am a beginner and would like to contribute to this project. I am not sure I fully understood the issue, but it sounds interesting. If you can guide me and provide me with some details I can try to solve the issue.

**Comment by stephen-hawley** [comment]
@ShrillShrestha - sorry I hadn't noticed this. If you want to take a look at the [PR](https://github.com/xamarin/binding-tools-for-swift/pull/540), you can see what I did to address this.
