### ISSUE TITLE
Sort out arm64 simulator issues

### ISSUE THREAD

**Issue by stephen-hawley** [xamarin/binding-tools-for-swift#684]
When building an iOS project in Xcode for simulator, you get `arm64-apple-ios-simulator` by default.
The problem we're seeing is that there is no `*MIN_VERSION` load command, but there is a `BUILD_VERSION` which we use instead of the `MIN_VERSION`. The problem is that the version that we get back has an OS and SDK version that is *way* different from the others, which causes us issues when we build against it.

We need to figure out how to make it build cleanly with `arm64-apple-ios-simulator`. It probably means tweaking the arguments to dynamically set the SDK information instead of using a static version.

**Comment by stephen-hawley** [comment]
I've cleaned up the code to handle the target quad and to compile code with "simulator", but a problem remains in that I don't know that we can build a fat version of XamGlue for iOS that can include arm64 and arm64-simulator. It raises questions like
- how does the dylib hold both arm64 and arm64-simulator since they're the same architecture?
- how is the Modules/XamGlue.swiftmodule directory laid out since it has files named arch.siwftmodule

**Comment by stephen-hawley** [comment]
It looks like you need to have an `.xcframework` and not a `.framework`

**Comment by spouliot** [comment]
FWIW the first mention of `.xcframework` I know of was done inside a Swift talk.
https://developer.apple.com/videos/play/wwdc2019/416/

The _nice_ thing is that an xcframework is just another directory structure over the existing framework one.
https://github.com/spouliot/xcframework

**Comment by stephen-hawley** [comment]
When this is done, remember to remove the code the skips arm64
