### ISSUE TITLE
Rename RetainNominalData/ReleaseNominalData to something else

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/binding-tools-for-swift#83]
Rename RetainNominalData/ReleaseNominalData to something else, since the nominal data isn't refcounted (even though any reference types contained within the nominal data is retained/released).

```csharp
RetainNominalData (foo);
RetainNominalData (foo);
ReleaseNominalData (foo);
ReleaseNominalData (foo);
```

doesn't work as expected

Steve suggested using the swift names `NominalInitializeWithCopy` and `NominalDestroy` instead.

**Comment by stephen-hawley** [comment]
Addressed in this [PR](https://github.com/xamarin/binding-tools-for-swift/pull/429)
