### ISSUE TITLE
[SoM] Improve parameter names in public APIs

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/binding-tools-for-swift#85]
Many of the parameter in SwiftRuntimeLibrary are named using a single letter: https://github.com/xamarin/maccore/blob/d18c6f84c231ad17bea7ab903479076c0a85efef/tools/tom-swifty/SwiftRuntimeLibrary/SwiftMarshal/StructMarshal.cs#L1152

We should come up with something better for public API.

**Comment by stephen-hawley** [comment]
Fixed in this [PR](https://github.com/xamarin/binding-tools-for-swift/pull/430)
